---
title: "Latent Space Model"
author: "Angela Yoon"
date: "9/2/2021"
output: pdf_document
---

```{r}
library(Rlab)
library(locfit)
```

```{r}
"
This code contains a function that can generate networks under the Latent
Space Model. Under this model, each member in the network is given a covariate, 
and the probability that a pair of members will have a connection depends
on the difference of the covariates (the 'distance' between the two).
"

expid_distance <- function(members,alpha,beta) {
  len <- length(members)
  G <- matrix(rep(0,len^2),len)
  
  for (i in 1:(len-1)) {
    for (j in (i+1):len) {
      
      i_coord <- members[i]
      j_coord <- members[j]
      
      prob <- expit(alpha-beta*(i_coord-j_coord)^2)
      
      edge <- rbern(1,prob)
      
      G[i,j] <- edge
      G[j,i] <- edge
    }
  }
  return(G)
}
```

```{r}
# sample run with covariate randomly generated from 
# normal distrubution of mean 10 and variance 1

members <- rnorm(10)

G2 <- expid_distance(members,10,15)
```
