---
title: "RDS Simulation on R with Sample Network"
author: "Angela Yoon"
date: "6/4/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### create the adjacency matrix for the original network G

G <- matrix(c(0,1,1,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1,0,0,1,1,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,1,0),9)
isSymmetric(G)

### build zero adjacency matrix that will be updated to output G_R

G_R <- matrix(rep(0,81),9)

### build zero matrix to keep track of waiting time

T <- matrix(rep(NA,81),9)

### create empty vector to keep track of order of recruitment

order <- c()
```

```{r}
### set initial values

lambda <- 0.5
n <- 8 ### total number of people wanted
i <- 1 ### index of starting vertex

order <- append(order,i)
```

```{r}
### iterate until we recruit n-1 more people

for (x in 1:(n-1)) {
  
  ### from original network, find all vertices adjacent to our most recently recruited vertex
  for (j in 1:9) {
    if (G[i,j] == 1) {
      ### "activate" corresponding edges by assigning a waiting time
      T[i,j] <- rexp(1, lambda)
    }
  }
  
  print(T)
  
  ### find the minimum waiting time from T to find out the next recruitment
  waiting_time <- min(T,na.rm = TRUE)
  new <- arrayInd(which.min(T),dim(T))
  
  ### identify the indexes of the recruiter and recruitee of this new recruitment
  recruiter <- new[1,1]
  recruitee <- new[1,2]
  
  ### update G_R and order to reflect this new recruitment
  G_R[recruiter,recruitee] <- 1
  order <- append(order,recruitee)
  
  print(G_R)
  print(order)
  
  ### update T by subtracting minimum waiting time from all other waiting times
  ### also deactivate all edges from any other vertex to recruitee
  for(row in 1:nrow(T)) {
    for(col in 1:ncol(T)) {
        if(!is.na(T[row, col])) {
          T[row,col] <- T[row,col]-waiting_time
        }
    }
  }
  T[,recruitee] <- rep(NA,9)
  
  ### update G by eliminating all edges to most recent recruiter and recruitee
  ### note: is there a need to do both? simplify if possible
  G[,recruiter] <- rep(0,9)
  G[,recruitee] <- rep(0,9)
  
  ### update i
  i <- new[1,2]

}
```

```{r}
### print output

print(G_R)
print(order)
```

