---
title: "RL sketch"
author: "Angela Yoon"
date: "11/11/2021"
output: pdf_document
---

```{r}
library(Rlab)
library(locfit)
```

```{r}
rds_simulation <- function(G, lambda, n, start_index, num_coupon) {
  
  ### build zero adjacency matrix that will be updated to output G_R
  size <- nrow(G)
  G_R <- matrix(rep(0,size^2),size)
  
  ### build zero matrix to keep track of waiting time
  T <- matrix(rep(NA,size^2),size)
  
  ### create empty vector to keep track of order of recruitment and waiting times
  order <- c(start_index)
  w <- c(0)
  
  ### create empty vector for covariates
  ### covariates have normal distribution of mean 0 and variance 1
  covariates <- c(rep(0,size))
  
  ### initialize i
  i <- start_index
  covariates[i] <- rnorm(1,0,1)
  
  ### iterate until we recruit n-1 more people
  for (x in 1:(n-1)) {
    
    ### from original network, find all vertices adjacent to our most recently recruited vertex
    for (j in 1:size) {
      if (G[i,j] == 1) {
        
        ### "activate" corresponding edges by assigning a waiting time
        ### but only if they are eligible for recruitment under a coin flip
        recruited <- rbern(1,expit(covariates[i]))
        if (recruited == 1) {
          T[i,j] <- rexp(1, lambda)
        }
      }
    }
    
    if (all(is.na(T))) {
      return(list(G_R, order, w))
    }
    
    ### find the minimum waiting time from T to find out the next recruitment
    waiting_time <- min(T,na.rm = TRUE)
    new <- arrayInd(which.min(T),dim(T))
    
    ### append minimum waiting time to vector w
    w <- append(w,waiting_time)
    
    ### identify the indexes of the recruiter and recruitee of this new recruitment
    recruiter <- new[1,1]
    recruitee <- new[1,2]
    
    ### update G_R and order to reflect this new recruitment
    G_R[recruiter,recruitee] <- 1
    order <- append(order,recruitee)
    
    ### update T by subtracting minimum waiting time from all other waiting times
    ### also deactivate all edges from any other vertex to recruitee
    ### also eliminate all waiting times from most recent recruiter if recruiter used all coupons
    for(row in 1:nrow(T)) {
      for(col in 1:ncol(T)) {
          if(!is.na(T[row, col])) {
            T[row,col] <- T[row,col]-waiting_time
          }
      }
    }
    T[,recruitee] <- rep(NA,size)
    if (sum(G_R[recruiter,])==2) {
      T[recruiter,] <- rep(NA,size)
    }
    
    ### update G by eliminating all edges to most recent recruiter and recruitee
    ### note: is there a need to do both? simplify if possible
    G[,recruiter] <- rep(0,size)
    G[,recruitee] <- rep(0,size)
    
    ### update i and covariate
    new_covariate <- rnorm(1,covariates[i],1)
    i <- new[1,2]
    covariates[i] <- new_covariate
  }
  
  return(list(G_R, order, w))
}
```

```{r}
results <- rds_simulation(G, 0.5, 90, 1, 3)
```


```{r}
simulation <- function(nseed,ncoupons) {
  
  # start with seeds
  # covariates have normal distribution of mean 0 and variance 1
  covariates <- rnorm(nseed,0,1)
  
  # degrees have poisson distribution of mean 3
  degrees <-  rpois(nseed,3)
  
  total_recruited <- nseed
  cumulative_list <- covariates
  
  # continue until out of coupons
  # detailing this part (when to stop) is not yet done
  while (total_recruited < ncoupons) {
    new_covariates <- c()
    
    # for each "seed", recruit some among its "degree" neighbors
    # whether each neighbor is recruited is a Bernoulli trial with 
    # p proportionate to seed covariate (proportionality established with expit)
    # if neighbor is recruited, it is given its own covariate
    # sampled from a normal distribution centered around the seed's covariate

    for (i in 1:length(covariates)) {
      for (j in 1:degrees[i]) {
        recruited <- rbern(1,expit(covariates[i]))
        if (recruited == 1) {
          new_covariates <- append(new_covariates,rnorm(1,covariates[i],1))
        }
      }
    }
    
    covariates <- new_covariates
    degrees <- rpois(length(covariates),3)
    total_recruited <- total_recruited + length(covariates)
    cumulative_list <- append(cumulative_list,covariates)
    
  }
  
  return(cumulative_list)
}
```

```{r}

```

