---
title: "Threshold"
author: "Angela Yoon"
date: "9/23/2021"
output: pdf_document
---

```{r}
"
Variation of the Crawford RDS Simulation.
Each person has a 'threshold', and recruitment is only made when the
offered 'coupon price (or payback)' is greater than the person's threshold
"

### creating the threshold vector

threshold <- rnorm(25,10,3)
threshold <- append(threshold,rnorm(30,35,5))
threshold <- append(threshold,rnorm(35,30,10))
```

```{r}
### recruitment with constant threshold

rds_simulation <- function(G, lambda, n, start_index, num_coupon, threshold, coupon_price) {
  
  ### build zero adjacency matrix that will be updated to output G_R
  size <- nrow(G)
  G_R <- matrix(rep(0,size^2),size)
  
  ### build zero matrix to keep track of waiting time
  T <- matrix(rep(NA,size^2),size)
  
  ### create empty coupon matrix C
  C <- matrix(rep(0,n*size),size)
  
  ### create empty vector to keep track of order of recruitment and waiting times
  order <- c(start_index)
  w <- c(0)
  
  ### initialize i
  i <- start_index
  
  ### iterate until we recruit n-1 more people
  for (x in 1:(n-1)) {
    
    ### from original network, find all vertices adjacent to our most recently recruited vertex
    for (j in 1:size) {
      ### activate only if recruitee has threshold lower than coupon price
      if (G[i,j] == 1 && threshold[j] < coupon_price) {
        ### "activate" corresponding edges by assigning a waiting time
        T[i,j] <- rexp(1, lambda)
      }
    }
    
    ### update C
    for (k in 1:size) {
      if (sum(T[k,],na.rm=TRUE)>0) {
        C[k,x] =1
      }
    }
    
    ### find the minimum waiting time from T to find out the next recruitment
    waiting_time <- min(T,na.rm = TRUE)
    new <- arrayInd(which.min(T),dim(T))
    
    ### append minimum waiting time to vector w
    w <- append(w,waiting_time)
    
    ### identify the indexes of the recruiter and recruitee of this new recruitment
    recruiter <- new[1,1]
    recruitee <- new[1,2]
    
    ### update G_R and order to reflect this new recruitment
    G_R[recruiter,recruitee] <- 1
    order <- append(order,recruitee)
    
    ### update T by subtracting minimum waiting time from all other waiting times
    ### also deactivate all edges from any other vertex to recruitee
    ### also eliminate all waiting times from most recent recruiter if recruiter used all coupons
    for(row in 1:nrow(T)) {
      for(col in 1:ncol(T)) {
          if(!is.na(T[row, col])) {
            T[row,col] <- T[row,col]-waiting_time
          }
      }
    }
    T[,recruitee] <- rep(NA,size)
    if (sum(G_R[recruiter,])==2) {
      T[recruiter,] <- rep(NA,size)
    }
    
    ### update G by eliminating all edges to most recent recruiter and recruitee
    ### note: is there a need to do both? simplify if possible
    G[,recruiter] <- rep(0,size)
    G[,recruitee] <- rep(0,size)
    
    ### update i
    i <- new[1,2]
  }
  
  return(list(G_R, order, w, C))
}
```

```{r}
results <- rds_simulation(G, 0.5, 42, 1, 3, threshold, 30)
```
